name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@v1

      # Setup Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'  # Specify the version of Flutter you need

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --output=none --set-exit-if-changed .

      # Analyze Flutter project
      # - name: Analyze project source
      #   run: flutter analyze

            # Run tests and generate coverage
      - name: Run tests with coverage
        run: flutter test --coverage  # No path needed, Flutter handles it

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
 

      # # Upload coverage reports to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Use GitHub secrets for security
          slug: inamhusain/flutter_background_process
